[package]
name = "steam-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simpleini = "0.1.2"
steam-api = "0.4.1"
chrono = "0.4"